services:
  app:
    build: .
    ports:
      - 33080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      DB_USER: root
      DB_PASS: root
    depends_on:
      - db
  db:
    image: surrealdb/surrealdb:nightly
    restart: always
    ports:
      - 33060:8000
    volumes:
      - db-data:/data
    environment:
      DB_PATH: file:/data # 配置数据库存储路径
      USER: root
      PASS: root
      BIND: 0.0.0.0:8000
      LOG: info
    command: start
    expose:
      - "8000"

volumes: 
  db-data: {}